//
// File: thrust2pwm.cpp
//
// MATLAB Coder version            : 3.0
// C/C++ source code generated on  : 06-Oct-2016 22:10:47
//

// Include Files
#include "thrust2pwm/thrust2pwm.h"

// Function Definitions

//
// THRUST2PWM
//     PWM = THRUST2PWM(VOLTAGE,THRUST)
// Arguments    : double voltage
//                double thrust
// Return Type  : double
//
double thrust2pwm(double voltage, double thrust)
{
  //     This function was generated by the Symbolic Math Toolbox version 6.3.
  //     06-Oct-2016 22:09:16
  return log(-((thrust - voltage * 5523.1786855393229) + 15320.8518522068) /
             (voltage * 5523.2364760913206 - 15320.94987982463)) *
    -16005.01978301193;
}

//
// File trailer for thrust2pwm.cpp
//
// [EOF]
//
