###################### CONSTANTS ###########################

mass: 1.25 # mass of the quadrotor [kg]
gravity: 9.806 # acceleration due to gravity [m/s^2]
l_arm: 0.1275 # quadrotor arm length
K_m: 0.05 # Dummy value for drag moment

# zyx - Euler for rotation from IMU frame to Copter frame
imu_rotation_yaw: 0.7854 # 45 degrees (z axis)
imu_rotation_pitch: 0.0000 # 0 degrees (y axis)
imu_rotation_roll: 3.1415 # 180 degrees (x axis)

# zyx - Euler for rotation from Copter frame to Camera frame
camera_roll_copter: 0
camera_pitch_copter: 0
camera_yaw_copter: -0.7854 # -45 degrees (z axis)

######################## MODEL #############################
state_init: [0,0,0,0,0,0,0,0,0,0,0,0] # [cartesian position [x,y,z], angular position (euler zyx) [x,y,z], cartesian velocity [x,y,z], angular velocity (euler zyx) [x,y,z]]
Jxx: 0.001120760 # inertia of the quadrotor x-axis [kg m^2]
Jyy: 0.001084620 # inertia of the quadrotor y-axis [kg m^2]
Jzz: 0.002083813 # inertia of the quadrotor z-axis [kg m^2]

###################### CONTROLLER ##########################
x_C_des: [1,0,0] # Desired x-axis of the quadrotor (equals more or less yaw angle)
K_P: [1,1,1]
K_V: [1,1,1]

###################### INITIAL_POSITION ####################
initial_altitude: 1.0
copter_x_init: 0.0
copter_y_init: -0.0
copter_yaw_init: 0.0

###################### POSITION_TRACKER ####################
video_file_path: "/home/TU-ilmenau/Robotik/04.avi"
# Path to video file
cam_number: 0 # OpenCV cam number, if negative it uses test video
cam_x_resolution: 320 # large: 640
cam_y_resolution: 240 # large: 480
cam_fps: 100 # 100 is maximum @ low res
use_inverse_image_filter: 1 # 0:no , 1:yes
BWtreshold: 181 #
inv_BWtreshold: 60 #
camera_constant: 282.0 #for low res 282, hight res 520
tolerated_deviationH: 1.8 #
tolerated_deviationW: 1.8 #
rects_of_interest_radius: 2.0 # radius in which rects from csv file are used for matching in one picture
image_send_rate: 5.0 # rate in Hz if under 0 it will not send

path_to_home: '/home/rosu/' #
path_to_trackdata: 'copteROS/src/copter/parameters/Trackdata.csv' #

################ EXTENDED KALMAN FILTER ###################
# variances for position, accelerometer, gyro and magnetometer
var_pos: [10, 10, 10] #[0.01, 0.01, 0.01]
var_acc: [0.02, 0.02, 0.02]
var_gyro: [0.03, 0.03, 0.03]
var_mag: [1, 1, 1]
process_var_pos: [0.005, 0.005, 0.005]
process_var_ang: [0.04, 0.04, 0.04]
process_var_vel: [0.1, 0.1, 0.1]
process_var_ang_vel: [0.1, 0.1, 0.1]
process_var_acc: [1000, 1000, 1000]
process_var_bias_acc: [0.001, 0.001 , 0.001]
process_var_bias_gyro: [0.001, 0.001, 0.001]


##################### Status #########################
motor_enable: 0 # enable pwm outputs for motor



